<?php

/**
 * Implements hook_preprocess_html().
 */
function pmsr_preprocess_html(&$variables) {
  $variables['attributes']['class'][] = 'pmsr-module-enabled';
}

/**
 * Implements hook_page_attachments().
 */
function pmsr_page_attachments(array &$attachments) {
  // Add the bootstrap library declared in the pmsr.libraries.yml file.
  $attachments['#attached']['library'][] = 'pmsr/bootstrap';
  $attachments['#attached']['library'][] = 'pmsr/pmsr-styles';
}


/**
 * Implements hook_block_view_alter().
 */
function pmsr_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  // Verifica se o bloco é o "block-hasco-barrio-page-title".
  if ($block->getBaseId() === 'page_title_block') {
    // Verifica se a rota atual é "pmsr.landing_page".
    if (\Drupal::routeMatch()->getRouteName() === 'pmsr.landing_page') {
      // Remove o conteúdo do bloco.
      $build = [];
    }
  }
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function pmsr_menu_links_discovered_alter(&$links) {
  if (isset($links['std.top_level'])) {
    $links['std.top_level']['title'] = 'Simulation Scenario';
    $links['std.top_level']['description'] = 'Manage Simulation Scenarios';

    $links['std.search_option']['title'] = 'Search Simulation Scenarios';
    $links['std.search_option']['description'] = 'Search Simulation Scenarios';

    $links['std.manage_studies']['title'] = 'Manage Simulation Scenarios';
    $links['std.manage_studies']['description'] = 'Manage Simulation Scenarios';
  }
}
